### ISSUE TITLE
The option to remove a password from a post is not saved unless you also do another modification to that post

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#95] opened 2014-08-05 21:56 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/2116

Steps to reproduce:
1. Go to posts
2. Select a post
3. Tap on Options
4. Make sure the post is protected by password
5. Change visibility to public

Expected result:
We would expect the post to be public.

Actual result:
The visibility remains password protected.
It will modify from password protected to public only if you modify something else too - such as the post itself (adding or deleting characters) or any other setting like the publish date, categories, post format - and press update.

We also mention that if you change the visibility from password protected to private the settings are saved.

Mention: tested on IOS iPad 7.1.2, iPhone 7.1.1 WP 4.1.3

---

Reproduced. The post needs to already be password protected before tapping on options. I changed my test post to public and saved. When i returned to the options screen it was still set as protected.

**Comment by diegoreymendez** [comment] 2016-03-10 15:02
Tested this both in the visual and legacy editor.  I could not reproduce this, and assume it's been fixed by now with our changes.

**Closed by diegoreymendez** 2016-03-10 15:02 UTC
Labels: bug
