### ISSUE TITLE
Editor tries to save draft without content

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-iOS#751] opened 2015-12-02 23:21 UTC
The editor will offer/try to save a draft that has had some changes to the post settings but no content (post content, title), resulting in an error. 

I consistently get an error message with these steps:

1. Open the editor
2. Open the post settings and change some settings on the post (e.g. change the category)
3. Try to exit the editor
4. The "You have unsaved changes" dialog opens, with options to Discard, Save Draft, or Keep Editing. Select "Save Draft."

Result: The editor closes and the error message "Error occurred during saving" appears.

Error in logs:
`2015/12/02 23:07:36:776  post failed: Content, title, and excerpt are empty. [empty_content]`

If the post can't be saved because it doesn't have any content, title, or excerpt, the app shouldn't offer to save the draft when exiting the editor. (I discovered this after I had already added a featured image to a post and changed some settings, but I wanted to exit the editor to check something before writing the post itself. I could have added a title before exiting if I had known the draft wouldn't save otherwise.)

When I tried to record a Lookback video of the issue, instead of giving that error message the app crashed.

Device: iPhone 6
iOS: 9.1
App: 5.8.0.20151124

**Comment by meremagee** [comment] 2015-12-02 23:23
related to https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/531; formerly fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/3286

**Comment by diegoreymendez** [comment] 2016-02-15 15:22
@rachelmcr, @meremagee - For new posts, we shouldn't let the user save an empty post.

But what's the expected behavior for posts in which the user removed all of the content before clicking the X button?

Should we ask the user if he wants to delete the post?

**Comment by rachelmcr** [comment] 2016-02-16 16:26
>Should we ask the user if he wants to delete the post?

That sounds reasonable to me. Theoretically the user might be trying to remove the post content without completely deleting it, but doesn't seem as likely.

**Comment by diegoreymendez** [comment] 2016-02-16 17:16
@rachelmcr - The current behavior is that when the user taps on X after deleting all the content, we simply cancel his post modification attempt and revert all changes.

I'm bringing this up because this would be a valid alternative.  Do you think the user would expect to be offered to delete the blog instead?  Just double checking ideas.

**Closed** 2016-02-16 20:23 UTC
Labels: bug

**Comment by rachelmcr** [comment] 2016-02-17 13:20
Ah, I understand now. I don't think we need to offer to delete it — the current behavior seems reasonable to me, and users can always delete the post from the post list if that is their intent. I haven't heard of confusion from users about this behavior, so I'd say we can leave it as is.

**Comment by diegoreymendez** [comment] 2016-02-17 14:06
Awesome, thanks @rachelmcr.
