### ISSUE TITLE
New post fails when adding category but no content

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#26] opened 2014-06-17 20:47 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/1496

1. Add a new post
1. Go directly to Options (collect $500 if so desired)
1. Add a category to the post.
1. Add a new category and select it for the post (this may be optional).
1. Go back to the post screen.
1. Click Save (or Publish) - notice it's enabled.
1. Notice Failed for a status.

**Comment by diegoreymendez** [comment] 2016-02-17 19:47
@astralbodies - I'm closing this as it seems to have been fixed by [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/4830).

I've tested this in the latest from `develop` in WPiOS and could not reproduce it.

**Closed by diegoreymendez** 2016-02-17 19:47 UTC
Labels: bug
