### ISSUE TITLE
Multi-paragraph blockquote support.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#499] opened 2015-01-22 16:04 UTC
As reported in [this lookback](https://lookback.io/watch/nGxBf4Dsi9R2Z7vyn).

**How to reproduce:**

- Write or paste a block of text in the editor, it needs to be in a single paragraph.
- Select the paragraph and press the blockquote toolbar item.
- Once the blockquote is displayed on screen place the caret anywhere in the middle of the blockquote.
- Press enter.

Current result: the blockquote is split into two blockquote blocks.
Expected result: the blockquote should remain a single blockquote with multiple paragraphs.

**IMPORTANT NOTE:** we should be checking the same for the "quote" toolbar item.

**Comment by diegoreymendez** [comment] 2015-02-06 18:10
Fixed.

**Comment by meremagee** [comment] 2015-03-11 19:41
I'm seeing some interesting multi-paragraph quote behavior in 5.0 develop: https://cloudup.com/c30rMlt5zmB

Expected: 
- quoting multiple paragraphs should preserve paragraph spacing
- while in a quote, hitting enter should keep you in quote and add new line (as it does), but tapping quote icon in format bar should then unquote that line and set cursor at beginning of new p. Here's what that looks like on wp-admin: https://cloudup.com/cWkrBFg0kXk

@bummytime - let's get a sanity check that post mutation isn't changing this and generally make sure there aren't regressions

**Comment by meremagee** [comment] 2015-03-13 16:45
closing here and opening a new issue with refinement specs

**Closed by meremagee** 2015-03-13 16:45 UTC
Labels: 2 - Working, enhancement, Lower Priority, new editor
